# Generated by Django 5.0.6 on 2024-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("isGDPRCompliant", models.BooleanField()),
                ("isSOXCompliant", models.BooleanField()),
                ("isPCICompliant", models.BooleanField()),
                ("isHIPAACompliant", models.BooleanField()),
                ("RTO", models.IntegerField()),
                ("RPO", models.IntegerField()),
                ("isDeleted", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("createdBy", models.CharField(max_length=100)),
                ("updatedBy", models.CharField(max_length=100)),
                ("deletedBy", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField()),
            ],
        ),
    ]
