# Generated by Django 5.0.6 on 2024-06-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="provider",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
